# Generated by Django 4.2.1 on 2023-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateField(null=True),
        ),
    ]
