# Generated by Django 4.2.1 on 2023-11-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_task_completed_completed_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.DeleteModel(
            name='Completed_tasks',
        ),
    ]
